### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by ethanquix** [nklayman/ca-dmv-poller#1]
How do you run this script ?

**Comment by nklayman** [comment]
Use the scripts added to your `package.json` by running these commands in the terminal:

For dev server:
`npm run electron:serve`
To build:
`npm run electron:build`

**Comment by ethanquix** [comment]
`npm ERR! missing script: electron:serve`
`npm ERR! missing script: electron:build`

The scripts seem to be missing

**Comment by nklayman** [comment]
try `npm run serve:electron` and `npm run build:electron`. The command names changed in 1.0.0-rc.4.

**Comment by nklayman** [comment]
Shoot, I thought this was my other repository ([vue-cli-plugin-electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder)). This app is currently broken due to the DMV working to block it. It is designed to be used in [CA DMV Appointment Fastfinder](https://play.google.com/store/apps/details?id=com.f12devs.CaDmvAppointmentFastFinder).

**Comment by nklayman** [comment]
They recently enabled recaptcha (I think), which prevents it from working. Sorry for misdirecting you.

**Comment by nklayman** [comment]
I got passed the recaptcha as of version 0.3.1. Try the app for android, or download it for windows/linux [here](https://drive.google.com/drive/folders/1KVNC30rTgzNDqrI8BMc2nBT0IZd6bWye).
